#!/bin/bash

(grep "^\** TODO" < $1) | sed "s/\** TODO //" |
while read line
do
	task add $line >&2

	if [ $# -ge 1 ]
	then
		task +LATEST annotate $(dirname $1)/$(basename $1) >&2
	fi
done

sed -E "s/^(\**) (TODO) (.*)$/\1 FILED \3/" $1 > $1.new
rm $1
mv $1.new $1
